sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t sornik/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sornik/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-536838829763"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access:key: "$AWS_SECRET_KEY"